#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

isH3Platform=false

detect_cpuinfo() {
	if [ "$CPUINFO_SUN8I" != "" ]; then
		isH3Platform=true

		# echo disabled > /sys/devices/virtual/thermal/thermal_zone0/mode

		# enable pull of hash power enable pins for board type detection
		echo PD0 1 > /sys/kernel/debug/sunxi_pinctrl/pull
		echo PD1 1 > /sys/kernel/debug/sunxi_pinctrl/pull
		echo PD2 1 > /sys/kernel/debug/sunxi_pinctrl/pull

		# bond irqs of uart1~3 to core1~3
		echo 2 > /proc/irq/33/smp_affinity
		echo 4 > /proc/irq/34/smp_affinity
		echo 8 > /proc/irq/35/smp_affinity
	fi
}

init_led() {
	if [ "$isH3Platform" = true ]; then
		echo 102 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio102/direction
		echo 103 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio103/direction
		echo 0 > /sys/class/gpio/gpio102/value
		echo 1 > /sys/class/gpio/gpio103/value
	else
		echo 943 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio943/direction
		echo 944 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio944/direction
		echo 0 > /sys/class/gpio/gpio943/value
		echo 1 > /sys/class/gpio/gpio944/value
	fi
}

set_reset_directions() {
	if [ "$isH3Platform" = true ]; then
		echo 99 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio99/direction
		echo 100 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio100/direction
		echo 101 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio101/direction
	else
		echo 960 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio960/direction
		echo 962 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio962/direction
		echo 964 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio964/direction
	fi
}

set_plug_directions() {
	if [ "$isH3Platform" = true ]; then
		echo 15 > /sys/class/gpio/export
		echo in > /sys/class/gpio/gpio15/direction
		echo 7 > /sys/class/gpio/export
		echo in > /sys/class/gpio/gpio7/direction
		echo 8 > /sys/class/gpio/export
		echo in > /sys/class/gpio/gpio8/direction
	else
		echo 961 > /sys/class/gpio/export
		echo in > /sys/class/gpio/gpio961/direction
		echo 963 > /sys/class/gpio/export
		echo in > /sys/class/gpio/gpio963/direction
		echo 965 > /sys/class/gpio/export
		echo in > /sys/class/gpio/gpio965/direction
	fi
}

set_en_directions() {
	if [ "$isH3Platform" = true ]; then
		echo 96 > /sys/class/gpio/export
		echo in > /sys/class/gpio/gpio96/direction
		echo 97 > /sys/class/gpio/export
		echo in > /sys/class/gpio/gpio97/direction
		echo 98 > /sys/class/gpio/export
		echo in > /sys/class/gpio/gpio98/direction
	else
		echo 934 > /sys/class/gpio/export
		echo in > /sys/class/gpio/gpio934/direction
		echo 939 > /sys/class/gpio/export
		echo in > /sys/class/gpio/gpio939/direction
		echo 937 > /sys/class/gpio/export
		echo in > /sys/class/gpio/gpio937/direction
	fi
}

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	uci commit
}

prepare_logs_partition() {
    mkdir -p /data/logs/

	if [ "$isH3Platform" = true ]; then
        mount -t ext4 /dev/nandh /data/logs
        if [ "$?" != "0" ]; then
            mke2fs -t ext4 -j -F /dev/nandh
            mount -t ext4 /dev/nandh /data/logs
        fi
    fi
}

boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /var/tmp
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	/bin/board_detect
	uci_apply_defaults

	detect_cpuinfo
	set_reset_directions
	set_plug_directions
	set_en_directions
	init_led

    prepare_logs_partition

	# temporary hack until configd exists
	/sbin/reload_config

	# create /dev/root if it doesn't exist
	[ -e /dev/root -o -h /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}
}
